package apiv2

import "net/http"

// externalSignInFixtureCases covers external sign-in (OIDC and LDAP auth
// plugins): discovery of the management operations, the account's linked
// identities, administrator identity management, the auth plugin
// connection test, the native OAuth handoff, link tickets and provider
// logout. Records are synthetic.
func externalSignInFixtureCases() []fixtureCase {
	problem := "#/components/schemas/Problem"
	schema := func(name string) string { return "#/components/schemas/" + name }
	json := []string{"Content-Type", "Cache-Control"}
	return []fixtureCase{
		{name: "get_external_sign_in_capabilities_ok", operationID: "getExternalSignInCapabilities",
			scenario: "An app discovers that the server links external sign-in identities and tests auth plugins.",
			method:   http.MethodGet, path: "/api/v2/auth/external-sign-in/capabilities",
			status: http.StatusOK, assertHeaders: json, schema: schema("ExternalSignInCapabilities")},
		{name: "list_account_identities_ok", operationID: "listAccountIdentities",
			scenario: "The account's Sign-in section lists the provider identity it is linked to.",
			method:   http.MethodGet, path: "/api/v2/account/identities", headers: bearer(memberToken),
			status: http.StatusOK, assertHeaders: json, schema: schema("AccountIdentityCollection")},
		{name: "delete_account_identity_last_sign_in_method", operationID: "deleteAccountIdentity",
			scenario: "Disconnecting the only way the account can sign in is refused.",
			method:   http.MethodDelete, path: "/api/v2/account/identities/4", headers: bearer(memberToken),
			status: http.StatusConflict, assertHeaders: json, schema: problem},
		{name: "delete_account_identity_ok", operationID: "deleteAccountIdentity",
			scenario: "Disconnecting an identity while the account can still sign in another way.",
			method:   http.MethodDelete, path: "/api/v2/account/identities/6", headers: bearer(memberToken),
			status: http.StatusNoContent, assertHeaders: []string{"Cache-Control"}},
		{name: "list_admin_user_identities_ok", operationID: "listAdminUserIdentities",
			scenario: "An administrator reads an account's linked identities, with the provider subject.",
			method:   http.MethodGet, path: "/api/v2/admin/users/1/identities", headers: actingRequestAdmin,
			status: http.StatusOK, assertHeaders: json, schema: schema("AdminUserIdentityCollection")},
		{name: "create_admin_user_identity_ok", operationID: "createAdminUserIdentity",
			scenario: "An administrator links an account to a provider identity by its exact subject.",
			method:   http.MethodPost, path: "/api/v2/admin/users/1/identities", headers: actingRequestAdmin,
			body:   `{"installation_id":"3","external_subject":"https://id.example.test/realms/silo|5d41402a","username":"alice"}`,
			status: http.StatusCreated, assertHeaders: append([]string{"Location"}, json...), schema: schema("AdminUserIdentity")},
		{name: "create_admin_user_identity_linked_elsewhere", operationID: "createAdminUserIdentity",
			scenario: "Linking an identity another account already holds.",
			method:   http.MethodPost, path: "/api/v2/admin/users/1/identities", headers: actingRequestAdmin,
			body:   `{"installation_id":"3","external_subject":"https://id.example.test/realms/silo|taken"}`,
			status: http.StatusConflict, assertHeaders: json, schema: problem},
		{name: "delete_admin_user_identity_ok", operationID: "deleteAdminUserIdentity",
			scenario: "An administrator unlinks an identity from an account.",
			method:   http.MethodDelete, path: "/api/v2/admin/users/1/identities/4", headers: actingRequestAdmin,
			status: http.StatusNoContent, assertHeaders: []string{"Cache-Control"}},
		{name: "test_admin_plugin_auth_binding_ok", operationID: "testAdminPluginAuthBinding",
			scenario: "An administrator tests staged OIDC settings; a failed check is a 200 result with ok false.",
			method:   http.MethodPost, path: "/api/v2/admin/plugins/installations/3/auth-binding/test", headers: actingRequestAdmin,
			body:   `{"capability_id":"oidc","config":[{"key":"oidc","value":{"issuer":"https://id.example.test","client_id":"silo","client_secret":""}}]}`,
			status: http.StatusOK, assertHeaders: json, schema: schema("AuthConnectionTestResult")},
		{name: "get_oauth_handshake_capabilities_ok", operationID: "getOAuthHandshakeCapabilities",
			scenario: "An app discovers that the server hands OAuth sign-in off to native apps and links identities.",
			method:   http.MethodGet, path: "/api/v2/auth/oauth/capabilities",
			status: http.StatusOK, assertHeaders: json, schema: schema("OAuthHandshakeCapabilitiesOutputBody")},
		{name: "complete_oauth_login_native_ok", operationID: "completeOAuthLogin",
			scenario: "A native app redeems the code the app redirect carried with its PKCE code verifier.",
			method:   http.MethodPost, path: "/api/v2/auth/oauth/complete", body: `{"code":"n4tive","code_verifier":"` + fixtureNativeVerifier + `"}`,
			status: http.StatusOK, assertHeaders: json, schema: schema("OAuthCompletion")},
		{name: "complete_oauth_login_invalid_grant", operationID: "completeOAuthLogin",
			scenario: "A native code redeemed without its code verifier is refused and stays redeemable.",
			method:   http.MethodPost, path: "/api/v2/auth/oauth/complete", body: `{"code":"n4tive"}`,
			status: http.StatusBadRequest, assertHeaders: json, schema: problem},
		{name: "create_account_identity_link_ticket_ok", operationID: "createAccountIdentityLinkTicket",
			scenario: "The account confirms its password and gets a ticket that starts a provider linking flow.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-ticket", headers: bearer(memberToken),
			body:   `{"installation_id":"3","password":"right password"}`,
			status: http.StatusOK, assertHeaders: json, schema: schema("AccountIdentityLinkTicket")},
		{name: "create_account_identity_link_ticket_wrong_password", operationID: "createAccountIdentityLinkTicket",
			scenario: "A wrong password is a validation problem at the password member.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-ticket", headers: bearer(memberToken),
			body:   `{"installation_id":"3","password":"wrong password"}`,
			status: http.StatusUnprocessableEntity, assertHeaders: json, schema: problem},
		{name: "start_account_identity_link_ok", operationID: "startAccountIdentityLink",
			scenario: "The web client starts a linking flow with its ticket; the binding cookie lands in this browser, which then opens the provider URL.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-start", headers: bearer(memberToken),
			body:   `{"link_ticket":"` + fixtureLinkTicket + `","next":"/settings/account"}`,
			status: http.StatusOK, assertHeaders: append([]string{"Set-Cookie"}, json...), schema: schema("AccountIdentityLinkStart")},
		{name: "start_account_identity_link_unknown_ticket", operationID: "startAccountIdentityLink",
			scenario: "A ticket that is used, expired or issued to another account starts nothing.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-start", headers: bearer(memberToken),
			body:   `{"link_ticket":"used-ticket"}`,
			status: http.StatusNotFound, assertHeaders: json, schema: problem},
		{name: "complete_account_identity_link_ok", operationID: "completeAccountIdentityLink",
			scenario: "The app confirms its linking flow with the code from the app redirect and its PKCE code verifier.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-complete", headers: bearer(memberToken),
			body:   `{"code":"` + fixtureLinkCode + `","code_verifier":"` + fixtureNativeVerifier + `"}`,
			status: http.StatusNoContent, assertHeaders: []string{"Cache-Control"}},
		{name: "complete_account_identity_link_invalid_grant", operationID: "completeAccountIdentityLink",
			scenario: "A link code redeemed with a verifier that does not fit is refused and stays redeemable.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-complete", headers: bearer(memberToken),
			body:   `{"code":"` + fixtureLinkCode + `","code_verifier":"wrong-verifier-wrong-verifier-wrong-verifier-x"}`,
			status: http.StatusBadRequest, assertHeaders: json, schema: problem},
		{name: "get_provider_logout_ok", operationID: "getProviderLogout",
			scenario: "The web client asks for the provider sign-out URL before it ends the Silo session.",
			method:   http.MethodGet, path: "/api/v2/auth/provider-logout", headers: bearer(memberToken),
			status: http.StatusOK, assertHeaders: json, schema: schema("ProviderLogout")},
		{name: "refresh_session_provider_unavailable", operationID: "refreshSession",
			scenario: "A session opened through the external sign-in provider is due for its provider re-check, the provider cannot be reached, and the outage policy is fail_closed: the session stays valid and the client retries later.",
			method:   http.MethodPost, path: "/api/v2/auth/refresh", body: `{"refresh_token":"provider-down"}`,
			status: http.StatusServiceUnavailable, assertHeaders: json, schema: problem},
		{name: "link_account_identity_with_credentials_ok", operationID: "linkAccountIdentityWithCredentials",
			scenario: "The account re-enters its password and links its directory (LDAP) identity with the directory username and password.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-credentials", headers: bearer(memberToken),
			body:   `{"installation_id":"4","password":"right password","username":"alice","directory_password":"directory password"}`,
			status: http.StatusCreated, assertHeaders: append([]string{"Location"}, json...), schema: schema("AccountIdentity")},
		{name: "link_account_identity_with_credentials_directory_refused", operationID: "linkAccountIdentityWithCredentials",
			scenario: "Directory credentials the directory refuses are a validation problem at the directory password member.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-credentials", headers: bearer(memberToken),
			body:   `{"installation_id":"4","password":"right password","username":"alice","directory_password":"wrong directory password"}`,
			status: http.StatusUnprocessableEntity, assertHeaders: json, schema: problem},
		{name: "approve_device_login_api_key_forbidden", operationID: "approveDeviceLogin",
			scenario: "An API key cannot approve a TV: an approval gives the device a login session, so only a signed-in session decides.",
			method:   http.MethodPost, path: "/api/v2/auth/device/approve", body: `{"code":"4821-7730"}`, headers: with(bearer(apiKeyToken), "X-Profile-Id", "p-primary"),
			status: http.StatusForbidden, assertHeaders: json, schema: problem},
		{name: "get_provider_logout_impersonation_empty", operationID: "getProviderLogout",
			scenario: "An administrator viewing as a linked account gets no provider sign-out, so the account's provider session and ID token stay with the account.",
			method:   http.MethodGet, path: "/api/v2/auth/provider-logout", headers: bearer(impersonatedToken),
			status: http.StatusOK, assertHeaders: json, schema: schema("ProviderLogout")},
		{name: "get_provider_logout_api_key_empty", operationID: "getProviderLogout",
			scenario: "An API key of a linked account gets no provider sign-out: it has no browser session at the provider to end.",
			method:   http.MethodGet, path: "/api/v2/auth/provider-logout", headers: bearer(apiKeyToken),
			status: http.StatusOK, assertHeaders: json, schema: schema("ProviderLogout")},
		{name: "login_account_required", operationID: "login",
			scenario: "The directory accepts the password, but the server has no account for the person and does not create one: an administrator has to add it (v1 answers not_permitted).",
			method:   http.MethodPost, path: "/api/v2/auth/login", body: `{"username":"newcomer","password":"directory password"}`,
			status: http.StatusForbidden, assertHeaders: json, schema: problem},
		{name: "admin_account_delete_break_glass_required", operationID: "deleteAdminUser",
			scenario: "Deleting the last break-glass administrator while local password sign-in is off is refused.",
			method:   http.MethodDelete, path: "/api/v2/admin/users/8", headers: with(actingRequestAdmin, "If-Match", "*"),
			status: http.StatusConflict, assertHeaders: json, schema: problem},
		{name: "sign_in_with_network_identity_ok", operationID: "signInWithNetworkIdentity",
			scenario: "A TV on the server's Tailscale network signs its owner in with no password: the body is an empty JSON object.",
			method:   http.MethodPost, path: "/api/v2/auth/network/5/sign-in", body: `{}`,
			status: http.StatusOK, assertHeaders: json, schema: schema("TokenPair")},
		{name: "sign_in_with_network_identity_off_overlay", operationID: "signInWithNetworkIdentity",
			scenario: "A request that did not come through the provider's network has no device owner to sign in.",
			method:   http.MethodPost, path: "/api/v2/auth/network/7/sign-in", body: `{}`,
			status: http.StatusForbidden, assertHeaders: json, schema: problem},
		{name: "link_account_identity_with_network_ok", operationID: "linkAccountIdentityWithNetwork",
			scenario: "The account re-enters its password and links the Tailscale identity of the device it is using.",
			method:   http.MethodPost, path: "/api/v2/account/identities/link-network", headers: bearer(memberToken),
			body:   `{"installation_id":"5","password":"right password"}`,
			status: http.StatusCreated, assertHeaders: append([]string{"Location"}, json...), schema: schema("AccountIdentity")},
	}
}
