package catalog

import (
	"context"
	"fmt"
	"log/slog"
	"maps"
	"slices"
	"strings"
	"time"

	"github.com/Silo-Server/silo-server/internal/models"
)

// A server collection without an uploaded or template poster shows a collage
// of its members' posters (collection_collages.go): each viewer sees the first
// members it can access, in collection order, so a restricted profile never
// sees the poster of a title it can't open (#1618).
// library_collections.poster_url holds only uploaded and template posters.

// collectionUsesLiveQuery reports whether the collection's members come from
// its query rather than its stored items, as ResolveLibraryCollectionMembership
// decides. Such a collection has no collage.
func collectionUsesLiveQuery(c *models.LibraryCollection) bool {
	return IsLiveQueryType(c.CollectionType)
}

// AssignedCollectionPoster returns the collection's uploaded or template
// poster, which every viewer shares. A poster_url marked auto-generated is the
// shared collage older servers stored, which is never served.
func AssignedCollectionPoster(c *models.LibraryCollection) (CollectionPoster, bool) {
	if strings.TrimSpace(c.PosterURL) == "" || c.PosterAutoGenerated {
		return CollectionPoster{}, false
	}
	return CollectionPoster{Path: c.PosterURL, Thumbhash: c.PosterThumbhash}, true
}

// ListCollectionCollageSources returns, for each collection, the poster paths
// of up to CollectionCollageSourceLimit members the viewer can access, in
// collection order. It applies the same access predicates as the collection's
// member list, so a collage never shows a member that list leaves out.
// Collections with no such member are absent from the result.
func (r *LibraryCollectionRepository) ListCollectionCollageSources(ctx context.Context, collectionIDs []string, access AccessFilter) (map[string][]string, error) {
	sources := make(map[string][]string, len(collectionIDs))
	if len(collectionIDs) == 0 || (access.AllowedLibraryIDs != nil && len(access.AllowedLibraryIDs) == 0) {
		return sources, nil
	}
	// A repeated ID would repeat its rows and double its sources.
	ids := slices.Clone(collectionIDs)
	slices.Sort(ids)
	sql, args := buildCollectionCollageSourcesSQL(slices.Compact(ids), access)
	rows, err := r.pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, fmt.Errorf("listing collection collage sources: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var id, path string
		if err := rows.Scan(&id, &path); err != nil {
			return nil, fmt.Errorf("scanning collection collage source: %w", err)
		}
		sources[id] = append(sources[id], path)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating collection collage sources: %w", err)
	}
	return sources, nil
}

func buildCollectionCollageSourcesSQL(collectionIDs []string, access AccessFilter) (string, []any) {
	args := []any{collectionIDs, CollectionCollageSourceLimit}
	argIdx := 3
	var memberWhere strings.Builder
	for _, condition := range itemAccessConditions(access, &args, &argIdx) {
		memberWhere.WriteString("\n\t\t\t  AND " + condition)
	}
	return `
		SELECT c.id, src.poster_path
		FROM unnest($1::text[]) WITH ORDINALITY AS c(id, ord)
		CROSS JOIN LATERAL (
			SELECT mi.poster_path, lci.position, lci.source_rank, lci.media_item_id
			FROM library_collection_items lci
			JOIN media_items mi ON mi.content_id = lci.media_item_id
			WHERE lci.collection_id = c.id
			  AND mi.poster_path <> ''` + memberWhere.String() + `
			ORDER BY lci.position, lci.source_rank, lci.media_item_id
			LIMIT $2
		) src
		ORDER BY c.ord, src.position, src.source_rank, src.media_item_id`, args
}

// GetCollectionCollages returns the stored collages among refs.
func (r *LibraryCollectionRepository) GetCollectionCollages(ctx context.Context, refs []CollectionCollageRef) (map[CollectionCollageRef]CollectionCollage, error) {
	collages := make(map[CollectionCollageRef]CollectionCollage, len(refs))
	if len(refs) == 0 {
		return collages, nil
	}
	ids, keys := splitCollectionCollageRefs(refs)
	rows, err := r.pool.Query(ctx, `
		SELECT v.collection_id, v.variant_key, v.poster_path, v.poster_thumbhash, v.last_used_at
		FROM unnest($1::text[], $2::text[]) AS ref(collection_id, variant_key)
		JOIN library_collection_poster_variants v
		  ON v.collection_id = ref.collection_id AND v.variant_key = ref.variant_key
	`, ids, keys)
	if err != nil {
		return nil, fmt.Errorf("loading collection collages: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var c CollectionCollage
		if err := rows.Scan(&c.CollectionID, &c.Key, &c.Path, &c.Thumbhash, &c.LastUsedAt); err != nil {
			return nil, fmt.Errorf("scanning collection collage: %w", err)
		}
		collages[c.CollectionCollageRef] = c
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating collection collages: %w", err)
	}
	return collages, nil
}

// TouchCollectionCollages records that refs were just served.
func (r *LibraryCollectionRepository) TouchCollectionCollages(ctx context.Context, refs []CollectionCollageRef) error {
	if len(refs) == 0 {
		return nil
	}
	ids, keys := splitCollectionCollageRefs(refs)
	if _, err := r.pool.Exec(ctx, `
		UPDATE library_collection_poster_variants v
		SET last_used_at = NOW()
		FROM unnest($1::text[], $2::text[]) AS ref(collection_id, variant_key)
		WHERE v.collection_id = ref.collection_id AND v.variant_key = ref.variant_key
	`, ids, keys); err != nil {
		return fmt.Errorf("touching collection collages: %w", err)
	}
	return nil
}

// SaveCollectionCollage stores a built collage, replacing one with the same
// key, and in the same transaction releases the path's reservation in the
// artwork revision collector's queue: the row now protects the objects. It
// returns ErrLibraryCollectionNotFound when the collection is gone, leaving the
// reservation for the collector.
func (r *LibraryCollectionRepository) SaveCollectionCollage(ctx context.Context, c CollectionCollage) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning collection collage save: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	tag, err := tx.Exec(ctx, `
		INSERT INTO library_collection_poster_variants (collection_id, variant_key, poster_path, poster_thumbhash)
		SELECT $1, $2, $3, $4
		WHERE EXISTS (SELECT 1 FROM library_collections WHERE id = $1)
		ON CONFLICT (collection_id, variant_key) DO UPDATE
		SET poster_path = EXCLUDED.poster_path,
		    poster_thumbhash = EXCLUDED.poster_thumbhash,
		    last_used_at = NOW()
	`, c.CollectionID, c.Key, c.Path, c.Thumbhash)
	if err != nil {
		return fmt.Errorf("saving collection collage: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrLibraryCollectionNotFound
	}
	if err := releaseCollectionCollageReservation(ctx, tx, c.Path); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("committing collection collage save: %w", err)
	}
	return nil
}

// RetireUnusedCollectionCollages deletes the collection's collages last
// served before cutoff and returns how many it deleted. The table's delete
// trigger hands their objects to the artwork revision collector in the same
// transaction.
func (r *LibraryCollectionRepository) RetireUnusedCollectionCollages(ctx context.Context, collectionID string, cutoff time.Time) (int, error) {
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM library_collection_poster_variants
		WHERE collection_id = $1 AND last_used_at < $2
	`, collectionID, cutoff)
	if err != nil {
		return 0, fmt.Errorf("retiring unused collection collages: %w", err)
	}
	return int(tag.RowsAffected()), nil
}

// ReserveCollectionCollagePath queues a collage path in the artwork revision
// collector before a collage is built under it; see reserveCollectionCollagePath.
func (r *LibraryCollectionRepository) ReserveCollectionCollagePath(ctx context.Context, path string) (held bool, err error) {
	return reserveCollectionCollagePath(ctx, r.pool, path)
}

// CollectionPosterWidths are the resized variants stored beside every
// original collection poster, uploaded or generated. The migration's
// queue_collection_poster_objects expands the same variants; change both
// together.
var CollectionPosterWidths = []int{500, 300}

// CollectionPosters returns the poster each collection shows the viewer
// described by access, keyed by collection ID. An uploaded or template poster
// is the same for every viewer. Otherwise the poster is the collage of the
// first members the viewer can access. A collage not built yet is left out of
// this answer and built in the background, so a later read finds it.
// Collections listed from a query have no collage. Collections with no poster
// are absent.
func (s *LibraryCollectionService) CollectionPosters(ctx context.Context, collections []*models.LibraryCollection, access AccessFilter) map[string]CollectionPoster {
	posters := make(map[string]CollectionPoster, len(collections))
	var collageIDs []string
	for _, c := range collections {
		if c == nil {
			continue
		}
		if poster, ok := AssignedCollectionPoster(c); ok {
			posters[c.ID] = poster
			continue
		}
		if !collectionUsesLiveQuery(c) {
			collageIDs = append(collageIDs, c.ID)
		}
	}
	if len(collageIDs) == 0 || s == nil || s.collections == nil || s.CollageGen == nil {
		return posters
	}

	sources, err := s.collections.ListCollectionCollageSources(ctx, collageIDs, access)
	if err != nil {
		slog.WarnContext(ctx, "collage: failed to select collection collages", "component", "catalog", "error", err)
		return posters
	}
	maps.Copy(posters, s.collageSet().serve(ctx, collageIDs, sources))
	return posters
}

// CollectionCollage returns one stored collage. Image requests that name a
// collage directly, such as a Jellyfin image tag, use it.
func (s *LibraryCollectionService) CollectionCollage(ctx context.Context, collectionID, key string) (CollectionPoster, bool, error) {
	if s == nil || s.collections == nil {
		return CollectionPoster{}, false, nil
	}
	ref := CollectionCollageRef{CollectionID: collectionID, Key: key}
	stored, err := s.collections.GetCollectionCollages(ctx, []CollectionCollageRef{ref})
	if err != nil {
		return CollectionPoster{}, false, err
	}
	c, ok := stored[ref]
	if !ok || c.Path == "" {
		return CollectionPoster{}, false, nil
	}
	if time.Since(c.LastUsedAt) > collectionCollageTouchInterval {
		if err := s.collections.TouchCollectionCollages(ctx, []CollectionCollageRef{ref}); err != nil {
			slog.DebugContext(ctx, "collage: failed to touch collection collages", "component", "catalog", "error", err)
		}
	}
	return CollectionPoster{Path: c.Path, Thumbhash: c.Thumbhash, CollageKey: key}, true, nil
}

// PrepareCollectionCollage builds the collage the viewer described by access
// sees for the collection, unless it is already stored. It returns
// collage.ErrNotEnoughImages when that viewer can access no member with a
// poster.
func (s *LibraryCollectionService) PrepareCollectionCollage(ctx context.Context, collectionID string, access AccessFilter) error {
	if s.CollageGen == nil {
		return nil
	}
	sources, err := s.collections.ListCollectionCollageSources(ctx, []string{collectionID}, access)
	if err != nil {
		return err
	}
	return s.collageSet().prepare(ctx, collectionID, sources[collectionID])
}

// buildCollage composes and stores one collage of a server collection.
func (s *LibraryCollectionService) buildCollage(ctx context.Context, ref CollectionCollageRef, sources []string) error {
	return s.collageSet().build(ctx, ref, sources)
}

// collageSet is the collage machinery over server collections' stored collages.
func (s *LibraryCollectionService) collageSet() collageSet {
	s.collageBuildsOnce.Do(func() { s.collageBuilds = newCollageBuildQueue() })
	return collageSet{store: s.collections, gen: s.CollageGen, queue: s.collageBuilds}
}
