package handlers

import (
	"bytes"
	"context"
	"image"
	"image/png"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Silo-Server/silo-server/internal/blobstore/blobstoretest"
	"github.com/Silo-Server/silo-server/internal/catalog"
	"github.com/Silo-Server/silo-server/internal/models"
)

// Responses build from withViewerPosters copies, so a shared collage an older
// server stored in poster_url never reaches a viewer, and the stored rows are
// left untouched.
func TestWithViewerPostersDropsLegacySharedCollage(t *testing.T) {
	h := &LibraryCollectionHandler{}
	uploaded := &models.LibraryCollection{ID: "uploaded", PosterURL: "collection-images/uploaded/poster/original.1.webp", PosterThumbhash: "th"}
	legacy := &models.LibraryCollection{ID: "legacy", PosterURL: "collection-images/legacy/poster/original.2.webp", PosterThumbhash: "old", PosterAutoGenerated: true}

	viewed := h.withViewerPosters(context.Background(), []*models.LibraryCollection{uploaded, nil, legacy}, catalog.AccessFilter{})
	if len(viewed) != 2 {
		t.Fatalf("viewed %d collections, want 2", len(viewed))
	}
	if viewed[0].PosterURL != uploaded.PosterURL || viewed[0].PosterThumbhash != "th" || viewed[0].PosterAutoGenerated {
		t.Fatalf("uploaded poster = %+v", viewed[0])
	}
	if viewed[1].PosterURL != "" || viewed[1].PosterThumbhash != "" {
		t.Fatalf("legacy collage served as %q / %q", viewed[1].PosterURL, viewed[1].PosterThumbhash)
	}
	if legacy.PosterURL == "" || viewed[1] == legacy {
		t.Fatal("withViewerPosters changed the stored collection instead of copying it")
	}
}

// collageSourceResolver resolves no plugin paths, so only http(s) sources
// reach the fetch.
type collageSourceResolver struct{}

func (collageSourceResolver) ResolveImageURL(context.Context, string, string) string { return "" }
func (collageSourceResolver) ResolveImageURLs(context.Context, []string, string) map[string]string {
	return map[string]string{}
}

func TestComposeCollectionCollageFailsWithoutEverySource(t *testing.T) {
	var poster bytes.Buffer
	if err := png.Encode(&poster, image.NewNRGBA(image.Rect(0, 0, 20, 30))); err != nil {
		t.Fatal(err)
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/missing.png" {
			http.Error(w, "gone", http.StatusServiceUnavailable)
			return
		}
		_, _ = w.Write(poster.Bytes())
	}))
	t.Cleanup(server.Close)

	detail := &catalog.DetailService{}
	detail.SetImageResolver(collageSourceResolver{})
	store := blobstoretest.New()
	h := &LibraryCollectionHandler{httpClient: server.Client(), ArtworkStore: store}
	h.SetDetailService(detail)

	const key = "0123456789abcdef"
	if _, _, err := h.ComposeCollectionCollage(t.Context(), "c1", key, []string{server.URL + "/a.png", server.URL + "/missing.png"}); err == nil {
		t.Fatal("a collage missing one of its sources was built")
	}
	if len(store.Objects) != 0 {
		t.Fatalf("a failed build stored %d objects", len(store.Objects))
	}

	// A source that doesn't resolve fails the build the same way.
	if _, _, err := h.ComposeCollectionCollage(t.Context(), "c1", key, []string{server.URL + "/a.png", "plugin://unresolvable/poster.jpg"}); err == nil {
		t.Fatal("a collage missing an unresolved source was built")
	}
	if len(store.Objects) != 0 {
		t.Fatalf("a failed build stored %d objects", len(store.Objects))
	}

	path, thumbhash, err := h.ComposeCollectionCollage(t.Context(), "c1", key, []string{server.URL + "/a.png", server.URL + "/b.png"})
	if err != nil {
		t.Fatalf("compose: %v", err)
	}
	if path != "collection-images/c1/collage/original."+key+".webp" || path != h.CollectionCollagePath("c1", key) || thumbhash == "" {
		t.Fatalf("stored %q with thumbhash %q", path, thumbhash)
	}
	keys := []string{path, "collection-images/c1/collage/w500." + key + ".webp", "collection-images/c1/collage/w300." + key + ".webp"}
	if len(keys) != len(store.Objects) {
		t.Fatalf("stored %d objects, want %v", len(store.Objects), keys)
	}
	for _, objectKey := range keys {
		if _, ok := store.Objects[objectKey]; !ok {
			t.Fatalf("object %s was not stored", objectKey)
		}
	}
}

// A library tab card marks the viewer's collage, and only that.
func TestLibraryTabCardsMarkViewerCollages(t *testing.T) {
	h := &LibraryCollectionHandler{}
	ctx := context.Background()
	if card := h.libraryTabCardOf(ctx, &models.LibraryCollection{ID: "collage", PosterURL: "/collage.webp", PosterAutoGenerated: true}); !card.PosterIsCollage {
		t.Fatalf("collage card = %+v, want PosterIsCollage", card)
	}
	if card := h.libraryTabCardOf(ctx, &models.LibraryCollection{ID: "uploaded", PosterURL: "/uploaded.webp"}); card.PosterIsCollage {
		t.Fatalf("uploaded card = %+v, want no PosterIsCollage", card)
	}
}
