import {
  Archive,
  Award,
  Bookmark,
  Cake,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Clapperboard,
  Dices,
  Flame,
  Gem,
  Globe,
  Headphones,
  Heart,
  History,
  Layers,
  ListFilter,
  MonitorPlay,
  Palette,
  Play,
  Shuffle,
  SkipForward,
  Smile,
  Sparkles,
  Star,
  Target,
  Timer,
  TrendingUp,
  Tv,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { RowGroup } from "@/lib/homeRows/catalog";

export const GROUP_ICONS: Record<RowGroup, LucideIcon> = {
  keep: Play,
  new: Sparkles,
  popular: Flame,
  picked: Heart,
  moods: Palette,
  collections: Layers,
};

/** Each picker group's tint, from the chart palette, for icon tiles. */
export const GROUP_TINTS: Record<RowGroup, string> = {
  keep: "bg-chart-1/15 text-chart-1 ring-chart-1/25",
  new: "bg-chart-2/15 text-chart-2 ring-chart-2/25",
  popular: "bg-chart-3/15 text-chart-3 ring-chart-3/25",
  picked: "bg-chart-4/15 text-chart-4 ring-chart-4/25",
  moods: "bg-chart-5/15 text-chart-5 ring-chart-5/25",
  collections: "bg-muted-foreground/15 text-muted-foreground ring-muted-foreground/25",
};

/** Each row kind's icon; kinds not listed use their group's icon. */
export const KIND_ICONS: Partial<Record<string, LucideIcon>> = {
  continue_watching: Play,
  next_up: SkipForward,
  next_in_series: Headphones,
  watchlist: Bookmark,
  favorites: Star,
  recently_added: Sparkles,
  recently_released: CalendarClock,
  new_to_library: CalendarPlus,
  returning_shows: Tv,
  trending_on_server: Flame,
  most_watched: TrendingUp,
  trending_discover: Globe,
  profile_activity_feed: Users,
  recommended_for_you: Heart,
  because_you_watched: History,
  similar_users_liked: Users,
  taste_match: Target,
  mood_collection: Smile,
  seasonal_themed: CalendarDays,
  editorial_spotlight: Clapperboard,
  format_showcase: MonitorPlay,
  hidden_gems: Gem,
  critically_acclaimed: Award,
  forgotten_favorites: Archive,
  genre_roulette: Dices,
  random: Shuffle,
  short_watches: Timer,
  anniversaries: Cake,
  award_winners: Award,
  collection: Layers,
  custom_filter: ListFilter,
  genre: ListFilter,
};
